### ISSUE TITLE
Headings are same size on Obsidian 0.13.27+

### ISSUE THREAD

**Issue by jorgb** [colineckert/obsidian-things#49] opened 2022-03-01 20:16 UTC
The heading 1 is small, and the same size as the other headings. Something in Obsidian 0.13.27 broke it. 

![image](https://user-images.githubusercontent.com/3519707/156241858-81a41d9f-2f95-4d0a-b9a4-d6617bbd8786.png)

This is what the inspect screen shows for heading 1when I copy the dom
```
<div class="HyperMD-header HyperMD-header-1 cm-line"><img class="cm-widgetBuffer"><span contenteditable="false"></span><img class="cm-widgetBuffer"><span class="cm-header cm-header-1">Tuesday 1 March 2022</span></div>
````

Heading 2
```
<div class="cm-active HyperMD-header HyperMD-header-2 cm-line"><img class="cm-widgetBuffer"><span contenteditable="false"></span><img class="cm-widgetBuffer"><span class="cm-header cm-header-2">Heading 2</span></div>
```

Hope this helps debugging the CSS problems

Thanks in advance!
- Jorgen

**Comment by jamietr1** [comment] 2022-03-03 12:32
I also noticed this. So far as I can tell, it appears broken in Live Preview, but not in read mode:

Live Preview:
![DFC_-_Obsidian_v0_13_27](https://user-images.githubusercontent.com/3660885/156565146-a1a42e51-5b3c-4733-9d3a-d2dcb1324a7e.png)

Read Mode:
![DFC_-_Obsidian_v0_13_27](https://user-images.githubusercontent.com/3660885/156565246-5a2d5242-c080-44b3-b009-ac2b58b2cf6e.png)

**Comment by colineckert** [comment] 2022-03-05 16:01
Hi all, thanks for your patience. This has been fixed in the latest version, so update your theme and let me know if the issue isn't resolved!

It appears something in the new Obsd update was overriding all my header font sizes, so just adding an `!important` flag on each (h1-h6) resolved it. Closing for now and thanks for creating the issue!

**Closed by colineckert** 2022-03-05 16:01 UTC

**Comment by jorgb** [comment] 2022-03-06 08:27
Thank you, things are peachy again :-)
