### ISSUE TITLE
Theme does not apply to pop-out windows

### ISSUE THREAD

**Issue by universvm** [colineckert/obsidian-things#72] opened 2022-07-13 17:14 UTC
Hi, 

This theme doesn't seem to work with the latest obsidian update for pop out windows.

![Screenshot 2022-07-13 at 18 14 16](https://user-images.githubusercontent.com/17524568/178792155-2164bcd0-61ed-49a5-b6bc-48c76764b52f.png)

**Comment by psyguy** [comment] 2022-07-27 11:50
Indeed. To make it more clear, if you open a note in a new window, Obsidian's default theme is applied to the poped out note.

**Comment by Jaques22** [comment] 2022-08-02 20:01
I have this issue as well, commenting to bump

**Comment by detonin** [comment] 2022-08-22 12:55
Same issue here. Theme does not apply to newly introduced pop out windows.
Any idea on how to fix this ?

**Comment by universvm** [comment] 2022-08-22 13:30
> Same issue here. Theme does not apply to newly introduced pop out windows. I suggest to rename this issue "Theme does not apply to pop-out windows" to make it more clear, and findable.
> 
> Any idea on how to fix this ?

Fixed the title. @colineckert  any news?

**Comment by mbentley** [comment] 2022-08-27 02:03
I was just looking at this and I am not sure why the css isn't loading for new windows.  Looking with developer tools, I just see that the css doesn't seem to be loading at all:
<img width="1680" alt="screenshot 2022-08-26 at 10 00 12 PM" src="https://user-images.githubusercontent.com/414445/187009902-ffe05478-1192-437b-9e8b-bf08b38539a7.png">

On the left, the main windows has the css file included in line but on the right hand side with the new window popped out, there's no css.  Still in developer tools, if I copy the style element from the left side to the right, it work as expected and all of the formatting shows as one would expect.

The odd thing that is that other themes seem to work just fine, for example, Minimal works fine as that's where I saw the behavior where the css is loaded on both the main window as well as the pop-out.

**Comment by kkharji** [comment] 2022-08-28 07:12
> The odd thing that is that other themes seem to work just fine, for example, Minimal works fine as that's where I saw the behavior where the css is loaded on both the main window as well as the pop-out.

Yeah thats what's driving me crazy. spent like 40 min switch between themes and non has that issue

**Comment by colineckert** [comment] 2022-08-28 21:21
Hey all. Thank you for posting in this issue thread and sharing your learnings! Jumping on this after addressing other issues first and this one is a pain in the ass lol. I thought it was an issue with race conditions but think something is broken in the CSS causing the entire style element not to be injected in the head tag of the new window, as @mbentley pointed out. Currently debugging the CSS to pinpoint the root cause and hope to have this fixed for everyone soon. Thanks for using the theme and sharing your feedback!

**Comment by colineckert** [comment] 2022-08-29 00:02
Hey all, this bug has _finally_ been fixed! Please update your theme to the latest version (v1.8). Closing this issue, but please reopen it if you experience any bugs. Thanks so much for supporting the development of this theme :)

**Closed by colineckert** 2022-08-29 00:02 UTC
