### ISSUE TITLE
YAML Syntax Highlighting is Not Working

### ISSUE THREAD

**Issue by JHHomeAssistant** [colineckert/obsidian-things#44] opened 2022-02-03 22:03 UTC
<img width="363" alt="Screen Shot 2022-02-03 at 5 03 32 PM" src="https://user-images.githubusercontent.com/97804892/152436646-d4004a37-8728-4634-ab4d-6b283d5b0e8c.png">

**Comment by colineckert** [comment] 2022-02-11 18:54
Thanks for creating the issue. I was not able to reproduce in dark mode. Can you confirm if you have any custom font settings and that the YAML frontmatter begins on the first line in the file?

![Screen Shot 2022-02-11 at 10 52 18 AM](https://user-images.githubusercontent.com/60206665/153652032-b4af5292-e38f-4bc3-9ea6-6483149c5713.png)

I appreciate the issue submission as it did inspire me to update the syntax highlighting in light mode, if that's of any value to you :) 
![Screen Shot 2022-02-11 at 10 53 49 AM](https://user-images.githubusercontent.com/60206665/153652226-e6a57c05-0494-41d7-b898-2d54a7a0c0b4.png)

**Comment by colineckert** [comment] 2023-03-10 18:08
Hello! Closing this issue as it should have resolved itself with Obsidian v1 and Things v2. Cheers!

**Closed by colineckert** 2023-03-10 18:08 UTC
